// Frontend reference for auto-generating specs by category
// ⚠️ Do NOT use at runtime outside admin forms

export const CATEGORY_SPEC_PRESETS: Record<string, Record<string, string>> = {
  phone: {
    brand: '',
    model: '',
    display_size: '',
    resolution: '',
    processor: '',
    ram: '',
    storage: '',
    battery_capacity: '',
    charging_type: '',
    operating_system: '',
    camera: '',
    connectivity: '',
    dimensions: '',
    weight: '',
  },

  laptop: {
    brand: '',
    model: '',
    processor: '',
    gpu: '',
    ram: '',
    storage: '',
    display_size: '',
    resolution: '',
    operating_system: '',
    battery_life: '',
    ports: '',
    dimensions: '',
    weight: '',
  },

  tablet: {
    brand: '',
    model: '',
    display_size: '',
    resolution: '',
    processor: '',
    ram: '',
    storage: '',
    operating_system: '',
    battery_capacity: '',
    camera: '',
    connectivity: '',
    stylus_support: '',
    dimensions: '',
    weight: '',
  },

  smartwatch: {
    brand: '',
    model: '',
    display_type: '',
    display_size: '',
    resolution: '',
    operating_system: '',
    battery_life: '',
    sensors: '',
    water_resistance: '',
    connectivity: '',
    compatibility: '',
    weight: '',
  },

  accessories: {
    material: '',
    compatibility: '',
    color: '',
    dimensions: '',
    weight: '',
  },

  ar_vr: {
    brand: '',
    model: '',
    display_type: '',
    resolution: '',
    refresh_rate: '',
    tracking: '',
    field_of_view: '',
    processor: '',
    battery_life: '',
    connectivity: '',
    weight: '',
  },
}
